MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  WEIGHT: "/z/home/vflorenc/maskrcnn-benchmark/networks/SRN_net.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 4000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("hsrc_srn_COCO_fgbg_train", "hsrc_srn_lab_bg_train", "hsrc_srn_lab_fgbg_train", "hsrc_srn_COCO_bg_train", "hsrc_srn_orig_train", "hsrc_srn_fg_train")
  TEST: ("hsrc_srn_COCO_fgbg_val", "hsrc_srn_lab_bg_val", "hsrc_srn_lab_fgbg_val", "hsrc_srn_COCO_bg_val", "hsrc_srn_orig_val", "hsrc_srn_fg_val")
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (7500, 10000)
  MAX_ITER: 25000
  CHECKPOINT_PERIOD: 1000
